required = ["github.com/sirupsen/logrus"]

[[constraint]]
  name = "github.com/ant0ine/go-json-rest"
  version = "3.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/uniuri"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

# docker/docker at the time of this writing depends on logrus 1.0.3:
# https://github.com/moby/moby/blob/705774aa7683892fc214d2b028d226f24ad20f1c/vendor.conf#L13
#
# As we don't use logrus directly from within habitus, and docker doesn't use dep, we need to explicitly mark it `required` and stick the version number like this:
# See https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-constrain-a-transitive-dependency-s-version for more details
#
# One more gotcha is that running `dep ensure` or even `dep ensure -update` doesn't update Gopkg.lock to catch up the logrus version set in Gopkg.toml.
# I suspect that it may be due to a bug in dep, but anyway, you need to manually update `Gopkg.lock` with the actual commit sha1 of 1.0.3 obtained from github:
# https://github.com/sirupsen/logrus/commit/f006c2ac4710855cf0f916dd6b77acf6b048dc6e
# After that, run `dep ensure -vendor-only` to update the vendored logrus.
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"
