build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile
      no_cache: false
      secrets:
        my_env_secret:
          type: env
          value: HOME